theme: jekyll-theme-minimal
title: "Learning Robot Structure and Pose Embeddings using Graph Neural Networks"
description: "ICML22 Workshop on ML in computational Design"
description: "J. Taery Kim, Jeongeun Park, Sungjoon Choi, Sehoon Ha"
google_analytics: 'G-F1HQVFCDJL'
